version: "2"
services:
  web:
    build: ./django
    ports:
        - "8080:80"
  worker:
    build: ./django
    command: python sevenpiece/manage.py runworker background-tasks
    links:
    - redis
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: sevenpiece
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - '3306:3306'
    expose:
      - '3306'
  redis:
    image: redis:6
    container_name: sevenpiece_local_redis
    ports:
      - "6379:6379"