version: "2"
services:
  web:
    build: ./django
    ports:
        - "80:80"
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: sevenpiece
    ports:
      - '3306:3306'
    volumes:
        - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    expose:
      - '3306'