version: "2"
services:
  web:
    build: ./django
    ports:
        - "80:80"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sevenpiece
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    expose:
      - '5432'
  redis:
    image: redis:6
    container_name: sevenpiece_local_redis
    ports:
      - "6379:6379"