# Generated by Django 3.2.5 on 2022-08-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('scheme', models.JSONField()),
                ('max_player_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('data', models.JSONField()),
                ('player_size', models.IntegerField()),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.colorscheme')),
            ],
        ),
    ]
