# Generated by Django 3.2.5 on 2022-08-30 21:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('special', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('scheme', models.JSONField()),
                ('max_player_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('session', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamestate')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('data', models.JSONField()),
                ('player_size', models.IntegerField()),
                ('num_characters', models.IntegerField()),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.colorscheme')),
            ],
        ),
        migrations.AddField(
            model_name='gamestate',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.map'),
        ),
    ]
