# Generated by Django 3.2.5 on 2022-09-13 21:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('health', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('special', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('attack_range_min', models.IntegerField(default=1)),
                ('attack_range_max', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('scheme', models.JSONField()),
                ('max_player_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('session', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('WAITING', 'Waiting for players'), ('READY', 'Ready to play'), ('PLACING', 'Placing pieces'), ('PLAYING', 'Game in progress'), ('FINISHED', 'Game Over')], default='WAITING', max_length=50)),
                ('turn_count', models.IntegerField(default=0)),
                ('objectives', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(default='', max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('number', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamestate')),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.IntegerField(null=True)),
                ('location_y', models.IntegerField(null=True)),
                ('health', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('point_value', models.IntegerField(default=1)),
                ('character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.character')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamestate')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('data', models.JSONField()),
                ('player_size', models.IntegerField()),
                ('num_characters', models.IntegerField()),
                ('score_to_win', models.IntegerField(default=5)),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.colorscheme')),
            ],
        ),
        migrations.AddField(
            model_name='gamestate',
            name='map',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.map'),
        ),
        migrations.CreateModel(
            name='IceWizard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.piece',),
        ),
    ]
