# Generated by Django 3.2.5 on 2022-08-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='num_characters',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
