# Generated by Django 3.2.13 on 2022-09-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='special_range',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='piece',
            name='special',
            field=models.IntegerField(default=0),
        ),
    ]
