# Generated by Django 3.2.13 on 2022-09-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='score_to_win',
            field=models.IntegerField(default=5),
        ),
    ]
