# Generated by Django 3.2.13 on 2022-09-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_map_score_to_win'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='point_value',
            field=models.IntegerField(default=1),
        ),
    ]
