# Generated by Django 3.2.13 on 2022-09-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20220915_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='attack',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='health',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='special',
            field=models.CharField(default='None', max_length=150),
        ),
        migrations.AlterField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='MapTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('data', models.JSONField()),
                ('player_size', models.IntegerField()),
                ('num_characters', models.IntegerField()),
                ('score_to_win', models.IntegerField(default=5)),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.colorscheme')),
            ],
        ),
    ]
