# Generated by Django 3.2.5 on 2022-08-27 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_map_num_characters'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('session', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.JSONField()),
                ('map', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.map')),
            ],
        ),
    ]
