# Generated by Django 3.2.13 on 2022-09-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_piece_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='objectives',
            field=models.CharField(default='', max_length=50),
        ),
    ]
