# Generated by Django 3.2.13 on 2022-09-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20220915_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='winner',
            field=models.IntegerField(default=-1),
        ),
    ]
