# Generated by Django 3.2.13 on 2022-09-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamestate_objectives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='attack_range',
            new_name='attack_range_max',
        ),
        migrations.AddField(
            model_name='character',
            name='attack_range_min',
            field=models.IntegerField(default=1),
        ),
    ]
