# Generated by Django 3.2.13 on 2022-09-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamestate_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='attack_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piece',
            name='health_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piece',
            name='speed_start',
            field=models.IntegerField(default=0),
        ),
    ]
