# Generated by Django 3.2.13 on 2022-09-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20220910_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='range',
            new_name='speed',
        ),
    ]
