# Generated by Django 3.2.5 on 2022-09-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20220905_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='player2',
        ),
        migrations.AddField(
            model_name='player',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='game.gamestate'),
            preserve_default=False,
        ),
    ]
