# Generated by Django 3.2.13 on 2022-09-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_range_piece_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceWizard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.piece',),
        ),
        migrations.RemoveField(
            model_name='player',
            name='user',
        ),
        migrations.AddField(
            model_name='player',
            name='session',
            field=models.CharField(default='', max_length=50),
        ),
    ]
