# Generated by Django 3.2.13 on 2022-10-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_player_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.piece',),
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.piece',),
        ),
        migrations.RenameField(
            model_name='character',
            old_name='special_range',
            new_name='special_range_max',
        ),
        migrations.AddField(
            model_name='character',
            name='special_range_min',
            field=models.IntegerField(default=1),
        ),
    ]
