# Generated by Django 3.2.13 on 2022-10-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20221006_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='special_range_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='special_range_min',
            field=models.IntegerField(default=0),
        ),
    ]
