# Generated by Django 3.2.13 on 2022-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20221007_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='state',
            field=models.CharField(default='normal', max_length=50),
        ),
    ]
