# Generated by Django 3.2.13 on 2022-09-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_piece_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='attack_range',
            field=models.IntegerField(default=1),
        ),
    ]
