# Generated by Django 3.2.13 on 2022-10-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_piece_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='state',
            field=models.CharField(choices=[('WAITING', 'Waiting for players'), ('SELECTING', 'Selecting pieces'), ('PLACING', 'Placing pieces'), ('PLAYING', 'Game in progress'), ('FINISHED', 'Game Over')], default='WAITING', max_length=50),
        ),
    ]
