# Generated by Django 3.2.13 on 2022-10-25 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20221015_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Werewolf',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('game.piece',),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='ended',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
