# Generated by Django 3.2.13 on 2022-10-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_gamestate_ended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
