# Generated by Django 3.2.13 on 2022-11-03 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_gamestate_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='start_turn_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
