# Generated by Django 3.2.13 on 2022-10-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_gamestate_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_computer',
            field=models.BooleanField(default=False),
        ),
    ]
