# Generated by Django 3.2.13 on 2022-10-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_player_is_computer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='single_player',
            field=models.BooleanField(default=False),
        ),
    ]
