# Generated by Django 3.2.13 on 2022-10-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_gamestate_single_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_computer',
        ),
    ]
