# Generated by Django 3.2.13 on 2022-11-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20221109_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='state',
            field=models.CharField(choices=[('IDLE', 'Not playing'), ('MATCHING', 'Waiting to join a match'), ('PLAYING', 'Currently playing a game')], default='IDLE', max_length=50),
        ),
    ]
