# Generated by Django 3.2.13 on 2022-11-10 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_player_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='session',
            field=models.CharField(default='', max_length=50),
        ),
    ]
