# Generated by Django 3.2.13 on 2022-11-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_player_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(default=-1),
        ),
    ]
