# Generated by Django 3.2.13 on 2022-11-10 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_player_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gamestate'),
        ),
    ]
