# Generated by Django 3.2.13 on 2022-11-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_piece_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='stats_damage_dealt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piece',
            name='stats_damage_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piece',
            name='stats_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piece',
            name='stats_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piece',
            name='stats_movements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piece',
            name='stats_objectives_captured',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piece',
            name='stats_wins',
            field=models.IntegerField(default=0),
        ),
    ]
