# Generated by Django 3.2.13 on 2022-11-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_auto_20221112_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='stats_deaths',
            field=models.IntegerField(default=0),
        ),
    ]
