# Generated by Django 3.2.13 on 2022-11-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_piece_stats_deaths'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stats_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='stats_wins',
            field=models.IntegerField(default=0),
        ),
    ]
