# Generated by Django 3.2.13 on 2022-11-29 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20221112_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='point_value',
        ),
        migrations.AddField(
            model_name='character',
            name='point_value',
            field=models.IntegerField(default=1),
        ),
    ]
