# Generated by Django 3.2.13 on 2022-12-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20221129_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='single_player',
            field=models.BooleanField(default=False),
        ),
    ]
